### PR TITLE
Modernize CMake code.

### PR DESCRIPTION
**Pull request by l0calh05t**
Convert -fvisibility=hidden to `CMAKE_<LANG>_VISIBILITY_PRESET`.
Convert -std=c99/-std=c++11 flags to `<LANG>_STANDARD(_REQUIRED)` and `<LANG>_EXTENSIONS`.

### CODE REVIEW

**Comment by andlabs** [comment]
Do the `STANDARD_REQUIRED` and `VISIBILITY` variables exist in 3.1.0? Just to make sure, because there are times I think the minimum version check doesn't check enough...

**Comment by andlabs** [comment]
Oops, forgot this PR. Will these variables require raising the minimum version of the CMakeLists file?

**Comment by l0calh05t** [comment]
No. All properties used in these commits are in CMake 3.1

**Comment by andlabs** [comment]
No longer relevant given the upcoming (either tomorrow or Tuesday) switch to Meson. Thanks anyway!

**Pull request closed without merging**
