### PR TITLE
Adds uiFormDelete()

### PR DESCRIPTION
**Pull request by emersion**
See #135

### CODE REVIEW

**Comment by andlabs** [comment]
If you take a closer look, you'll see that the OS X implementation of `-[formView delete:]` doesn't exist

**Comment by emersion** [comment]
Well, that's the only platform on which I didn't tests because I haven't any OS X device :(

**Comment by emersion** [comment]
Okay, just tried to add `-[formView delete:]`. No idea if it works though.

**Comment by emersion** [comment]
Just updated darwin. I pulled changes you made yesterday on master and tested it on a real macOS device.

**Comment by andlabs** [comment]
Cool, thanks. I'll read through this again in a bit and merge it (making fixes as necessary; again, very subtle stuff). Good work!

**Pull request merged**
