### PR TITLE
button: add uiButtonSetMinSize to avoid very small buttons

### PR DESCRIPTION
**Pull request by RustamGamidov**
it looks not very nice for example in the OK - Cancel dialogues

### CODE REVIEW

**Comment by RustamGamidov** [comment]
macos ci is failing at the checkout statge.
ci UI is different from the one ~one week ago so this could be the reason

**Comment by andlabs** [comment]
Hi. You do not need to keep closing and re-opening new pull requests. I will process this when I can, but I did see it the first time. Thanks in the meantime!

**Comment by RustamGamidov** [comment]
sorry for the noise. it's because of nominmax in the MSVS

**Comment by andlabs** [comment]
Oh, I see — no, you do not need to file a new PR every time you make changes. Just upload to your forked branch and github will pick up the changes.

**Comment by RustamGamidov** [comment]
github is updating opened PR with the changes pushed to the original branch.
Sometimes there are regexp masks for the PR titles to skip CI like [WIP] or so, not sure if it's the case.

And i'm using mingw locally so everything was fine for me (as it usually is :) )
Really sorry about all that extra builds

**Comment by andlabs** [comment]
Huh, that's new to me, and it would definitely inhibit contribution. I'll need to look into that. Sorry for snapping earlier!

**Pull request closed without merging**
