### PR TITLE
Fix windows static copy

### LINKED ISSUE #110: Error copying file "/CMakeFiles/libui.dir/windows/resources.rc.obj" to "D:/libui/build/out/libui.res".
Windows 10 64-bit
gcc version 5.2.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

```
D:\libui\build [master...origin/master +1 ~0 -0 !]> cmake -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF ..
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Check for working C compiler: C:/mingw/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/mingw/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/mingw/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/mingw/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/libui/build

D:\libui\build [master...origin/master +1 ~0 -0 !]> mingw32-make
Scanning dependencies of target libui
[  1%] Building C object CMakeFiles/libui.dir/common/areaevents.c.obj
[  3%] Building C object CMakeFiles/libui.dir/common/control.c.obj
[  5%] Building C object CMakeFiles/libui.dir/common/debug.c.obj
[  6%] Building C object CMakeFiles/libui.dir/common/matrix.c.obj
[  8%] Building C object CMakeFiles/libui.dir/common/shouldquit.c.obj
[ 10%] Building C object CMakeFiles/libui.dir/common/userbugs.c.obj
[ 12%] Building CXX object CMakeFiles/libui.dir/windows/alloc.cpp.obj
[ 13%] Building CXX object CMakeFiles/libui.dir/windows/area.cpp.obj
[ 15%] Building CXX object CMakeFiles/libui.dir/windows/areadraw.cpp.obj
[ 17%] Building CXX object CMakeFiles/libui.dir/windows/areaevents.cpp.obj
[ 18%] Building CXX object CMakeFiles/libui.dir/windows/areascroll.cpp.obj
D:\libui\windows\areascroll.cpp:137:13: warning: 'void hscrollto(uiArea*, intmax_t)' defined but not used [-Wunused-func
tion]
 static void hscrollto(uiArea *a, intmax_t pos)
             ^
D:\libui\windows\areascroll.cpp:182:13: warning: 'void vscrollto(uiArea*, intmax_t)' defined but not used [-Wunused-func
tion]
 static void vscrollto(uiArea *a, intmax_t pos)
             ^
[ 20%] Building CXX object CMakeFiles/libui.dir/windows/areautil.cpp.obj
[ 22%] Building CXX object CMakeFiles/libui.dir/windows/box.cpp.obj
D:\libui\windows\box.cpp: In function 'void boxRelayout(uiBox*)':
D:\libui\windows\box.cpp:86:5: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
  if (nStretchy != 0)
     ^
D:\libui\windows\box.cpp:38:12: warning: unused variable 'i' [-Wunused-variable]
  uintmax_t i;
            ^
D:\libui\windows\box.cpp:40:19: warning: unused variable 'd' [-Wunused-variable]
  uiWindowsSizing *d;
                   ^
D:\libui\windows\box.cpp: In function 'void uiBoxMinimumSize(uiWindowsControl*, intmax_t*, intmax_t*)':
D:\libui\windows\box.cpp:160:12: warning: unused variable 'i' [-Wunused-variable]
  uintmax_t i;
            ^
D:\libui\windows\box.cpp:162:18: warning: unused variable 'sizing' [-Wunused-variable]
  uiWindowsSizing sizing;
                  ^
D:\libui\windows\box.cpp: In function 'void boxArrangeChildren(uiBox*)':
D:\libui\windows\box.cpp:233:12: warning: unused variable 'i' [-Wunused-variable]
  uintmax_t i;
            ^
[ 24%] Building CXX object CMakeFiles/libui.dir/windows/button.cpp.obj
[ 25%] Building CXX object CMakeFiles/libui.dir/windows/checkbox.cpp.obj
[ 27%] Building CXX object CMakeFiles/libui.dir/windows/colorbutton.cpp.obj
[ 29%] Building CXX object CMakeFiles/libui.dir/windows/colordialog.cpp.obj
D:\libui\windows\colordialog.cpp: In function 'void hsv2RGB(double, double, double, double*, double*, double*)':
D:\libui\windows\colordialog.cpp:90:9: warning: unused variable 'c1' [-Wunused-variable]
  double c1, c2;
         ^
D:\libui\windows\colordialog.cpp:90:13: warning: unused variable 'c2' [-Wunused-variable]
  double c1, c2;
             ^
D:\libui\windows\colordialog.cpp: In function 'HWND__* replaceWithD2DScratch(HWND, int, SUBCLASSPROC, void*)':
D:\libui\windows\colordialog.cpp:868:43: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  return newD2DScratch(parent, &r, (HMENU) id, subproc, (DWORD_PTR) data);
                                           ^
[ 31%] Building CXX object CMakeFiles/libui.dir/windows/combobox.cpp.obj
[ 32%] Building CXX object CMakeFiles/libui.dir/windows/container.cpp.obj
[ 34%] Building CXX object CMakeFiles/libui.dir/windows/control.cpp.obj
[ 36%] Building CXX object CMakeFiles/libui.dir/windows/d2dscratch.cpp.obj
[ 37%] Building CXX object CMakeFiles/libui.dir/windows/datetimepicker.cpp.obj
[ 39%] Building CXX object CMakeFiles/libui.dir/windows/debug.cpp.obj
D:\libui\windows\debug.cpp: In function 'HRESULT _logLastError(const WCHAR*, const WCHAR*, const WCHAR*, const WCHAR*)':
D:\libui\windows\debug.cpp:22:13: warning: ISO C++ forbids converting a string constant to 'WCHAR* {aka wchar_t*}' [-Wpe
dantic]
   formatted = L"\n";
             ^
D:\libui\windows\debug.cpp: In function 'HRESULT _logHRESULT(const WCHAR*, const WCHAR*, const WCHAR*, const WCHAR*, HRE
SULT)':
D:\libui\windows\debug.cpp:49:13: warning: ISO C++ forbids converting a string constant to 'WCHAR* {aka wchar_t*}' [-Wpe
dantic]
   formatted = L"\n";
             ^
[ 41%] Building CXX object CMakeFiles/libui.dir/windows/draw.cpp.obj
[ 43%] Building CXX object CMakeFiles/libui.dir/windows/drawmatrix.cpp.obj
[ 44%] Building CXX object CMakeFiles/libui.dir/windows/drawpath.cpp.obj
[ 46%] Building CXX object CMakeFiles/libui.dir/windows/drawtext.cpp.obj
D:\libui\windows\drawtext.cpp: In function 'uiDrawTextFont* mkTextFont(IDWriteFont*, BOOL, WCHAR*, BOOL, double)':
D:\libui\windows\drawtext.cpp:64:10: warning: unused variable 'hr' [-Wunused-variable]
  HRESULT hr;
          ^
D:\libui\windows\drawtext.cpp: In function 'void dwriteAttrToAttr(dwriteAttr*)':
D:\libui\windows\drawtext.cpp:177:15: warning: variable 'curindex' set but not used [-Wunused-but-set-variable]
  int curdiff, curindex;
               ^
D:\libui\windows\drawtext.cpp: In function 'void uiDrawText(uiDrawContext*, double, double, uiDrawTextLayout*)':
D:\libui\windows\drawtext.cpp:502:10: warning: unused variable 'hr' [-Wunused-variable]
  HRESULT hr;
          ^
[ 48%] Building CXX object CMakeFiles/libui.dir/windows/dwrite.cpp.obj
[ 50%] Building CXX object CMakeFiles/libui.dir/windows/editablecombo.cpp.obj
[ 51%] Building CXX object CMakeFiles/libui.dir/windows/entry.cpp.obj
D:\libui\windows\entry.cpp: In function 'uiEntry* uiNewSearchEntry()':
D:\libui\windows\entry.cpp:126:10: warning: variable 'hr' set but not used [-Wunused-but-set-variable]
  HRESULT hr;
          ^
[ 53%] Building CXX object CMakeFiles/libui.dir/windows/events.cpp.obj
D:\libui\windows\events.cpp: In function 'void issueWM_WININICHANGE(WPARAM, LPARAM)':
D:\libui\windows\events.cpp:147:23: warning: unused variable 'ch' [-Wunused-variable]
  struct wininichange *ch;
                       ^
[ 55%] Building CXX object CMakeFiles/libui.dir/windows/fontbutton.cpp.obj
[ 56%] Building CXX object CMakeFiles/libui.dir/windows/fontdialog.cpp.obj
D:\libui\windows\fontdialog.cpp: In function 'void fontDialogDrawSampleText(fontDialog*, ID2D1RenderTarget*)':
D:\libui\windows\fontdialog.cpp:367:10: warning: ISO C++ forbids converting a string constant to 'WCHAR* {aka wchar_t*}'
 [-Wpedantic]
   sample = L"The quick brown fox jumps over the lazy dog.";
          ^
[ 58%] Building CXX object CMakeFiles/libui.dir/windows/graphemes.cpp.obj
[ 60%] Building CXX object CMakeFiles/libui.dir/windows/group.cpp.obj
[ 62%] Building CXX object CMakeFiles/libui.dir/windows/init.cpp.obj
D:\libui\windows\init.cpp: In function 'const char* initerr(const char*, const WCHAR*, DWORD)':
D:\libui\windows\init.cpp:24:10: warning: ISO C++ forbids converting a string constant to 'WCHAR* {aka wchar_t*}' [-Wped
antic]
   sysmsg = L"";
          ^
[ 63%] Building CXX object CMakeFiles/libui.dir/windows/label.cpp.obj
[ 65%] Building CXX object CMakeFiles/libui.dir/windows/main.cpp.obj
[ 67%] Building CXX object CMakeFiles/libui.dir/windows/menu.cpp.obj
[ 68%] Building CXX object CMakeFiles/libui.dir/windows/multilineentry.cpp.obj
[ 70%] Building CXX object CMakeFiles/libui.dir/windows/parent.cpp.obj
[ 72%] Building CXX object CMakeFiles/libui.dir/windows/progressbar.cpp.obj
[ 74%] Building CXX object CMakeFiles/libui.dir/windows/radiobuttons.cpp.obj
D:\libui\windows\radiobuttons.cpp: In function 'BOOL onWM_COMMAND(uiControl*, HWND, WORD, LRESULT*)':
D:\libui\windows\radiobuttons.cpp:21:12: warning: unused variable 'i' [-Wunused-variable]
  uintmax_t i;
            ^
[ 75%] Building CXX object CMakeFiles/libui.dir/windows/separator.cpp.obj
[ 77%] Building CXX object CMakeFiles/libui.dir/windows/sizing.cpp.obj
[ 79%] Building CXX object CMakeFiles/libui.dir/windows/slider.cpp.obj
D:\libui\windows\slider.cpp:29:51: warning: extra ';' [-Wpedantic]
 uiWindowsControlAllDefaultsExceptDestroy(uiSlider);
                                                   ^
[ 81%] Building CXX object CMakeFiles/libui.dir/windows/spinbox.cpp.obj
[ 82%] Building CXX object CMakeFiles/libui.dir/windows/stddialogs.cpp.obj
[ 84%] Building CXX object CMakeFiles/libui.dir/windows/tab.cpp.obj
[ 86%] Building CXX object CMakeFiles/libui.dir/windows/tabpage.cpp.obj
[ 87%] Building CXX object CMakeFiles/libui.dir/windows/text.cpp.obj
[ 89%] Building CXX object CMakeFiles/libui.dir/windows/utf16.cpp.obj
[ 91%] Building CXX object CMakeFiles/libui.dir/windows/utilwin.cpp.obj
[ 93%] Building CXX object CMakeFiles/libui.dir/windows/window.cpp.obj
D:\libui\windows\window.cpp: In function 'void windowRelayout(uiWindow*)':
D:\libui\windows\window.cpp:38:18: warning: unused variable 'sizing' [-Wunused-variable]
  uiWindowsSizing sizing;
                  ^
D:\libui\windows\window.cpp: In function 'void uiWindowMinimumSize(uiWindowsControl*, intmax_t*, intmax_t*)':
D:\libui\windows\window.cpp:227:18: warning: unused variable 'sizing' [-Wunused-variable]
  uiWindowsSizing sizing;
                  ^
[ 94%] Building CXX object CMakeFiles/libui.dir/windows/winpublic.cpp.obj
[ 96%] Building CXX object CMakeFiles/libui.dir/windows/winutil.cpp.obj
[ 98%] Building RC object CMakeFiles/libui.dir/windows/resources.rc.obj
[100%] Linking CXX static library out\libui.a
Copying libui.res
Error copying file "/CMakeFiles/libui.dir/windows/resources.rc.obj" to "D:/libui/build/out/libui.res".
CMakeFiles\libui.dir\build.make:1597: recipe for target 'out/libui.a' failed
mingw32-make[2]: *** [out/libui.a] Error 1
mingw32-make[2]: *** Deleting file 'out/libui.a'
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/libui.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/libui.dir/all] Error 2
makefile:82: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
D:\libui\build [master...origin/master +1 ~0 -0 !]>
```

### LINKED ISSUE #133: Cross compiling almost works
```
[ 98%] Building RC object CMakeFiles/libui.dir/windows/resources.rc.res
[100%] Linking CXX static library out/libui.a
Copying libui.res
Error copying file "/home/simon/projects/libui/build-w64/CMakeFiles/libui.dir/windows/resources.rc.obj" to "/home/simon/projects/libui/build-w64/out/libui.res".
CMakeFiles/libui.dir/build.make:1652: recipe for target 'out/libui.a' failed
make[2]: *** [out/libui.a] Error 1
make[2]: *** Deleting file 'out/libui.a'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/libui.dir/all' failed
make[1]: *** [CMakeFiles/libui.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

(See https://wiki.archlinux.org/index.php/MinGW_package_guidelines#CMake to do it: `x86_64-w64-mingw32-cmake .. -DBUILD_SHARED_LIBS=OFF`)

### PR DESCRIPTION
**Pull request by emersion**
Adds a wildcard instead of trying to detect extension.

Fixes #133
Fixes #110

### CODE REVIEW

**Comment by andlabs** [comment]
I guess this will do. Thanks!

**Comment by padicao2010** [comment]
@andlabs 

It seems that it uses "copy" command to copy, and "copy" does not support "*".

Error shows like:

```
E:\Tools\cmake-3.6.1-win64-x64\bin\cmake.exe -E copy E:/Workspace/libui/libui-bu
ild/CMakeFiles/libui.dir/windows/resources.rc.* E:/Workspace/libui/libui-build/o
ut/libui.res
Error copying file "E:/Workspace/libui/libui-build/CMakeFiles/libui.dir/windows/
resources.rc.*" to "E:/Workspace/libui/libui-build/out/libui.res".
CMakeFiles\libui.dir\build.make:1651: recipe for target 'out/libui.a' failed
```

**Comment by andlabs** [comment]
Can you provide a directory listing of `E:/Workspace/libui/libui-build/CMakeFiles/libui.dir/windows/`?

**Comment by padicao2010** [comment]
The directory listing:

```
2016/07/26  13:13    <DIR>          .
2016/07/26  13:13    <DIR>          ..
2016/07/26  13:12           877,075 alloc.cpp.obj
2016/07/26  13:12           239,678 area.cpp.obj
2016/07/26  13:12           230,969 areadraw.cpp.obj
2016/07/26  13:12           237,536 areaevents.cpp.obj
2016/07/26  13:12           234,855 areascroll.cpp.obj
2016/07/26  13:12           227,392 areautil.cpp.obj
2016/07/26  13:12           357,625 box.cpp.obj
2016/07/26  13:12           234,851 button.cpp.obj
2016/07/26  13:12           235,632 checkbox.cpp.obj
2016/07/26  13:12           239,047 colorbutton.cpp.obj
2016/07/26  13:12           530,182 colordialog.cpp.obj
2016/07/26  13:12           235,704 combobox.cpp.obj
2016/07/26  13:12           230,471 container.cpp.obj
2016/07/26  13:12           231,234 control.cpp.obj
2016/07/26  13:12           231,877 d2dscratch.cpp.obj
2016/07/26  13:12           238,335 datetimepicker.cpp.obj
2016/07/26  13:12           226,973 debug.cpp.obj
2016/07/26  13:12           340,824 draw.cpp.obj
2016/07/26  13:12           238,598 drawmatrix.cpp.obj
2016/07/26  13:12           232,590 drawpath.cpp.obj
2016/07/26  13:12           342,650 drawtext.cpp.obj
2016/07/26  13:12           229,508 dwrite.cpp.obj
2016/07/26  13:12           236,750 editablecombo.cpp.obj
2016/07/26  13:12           236,508 entry.cpp.obj
2016/07/26  13:12           589,042 events.cpp.obj
2016/07/26  13:12           235,870 fontbutton.cpp.obj
2016/07/26  13:12           253,918 fontdialog.cpp.obj
2016/07/26  13:13           359,103 form.cpp.obj
2016/07/26  13:13           227,095 graphemes.cpp.obj
2016/07/26  13:13           540,706 grid.cpp.obj
2016/07/26  13:13           238,292 group.cpp.obj
2016/07/26  13:13           233,081 init.cpp.obj
2016/07/26  13:13           232,930 label.cpp.obj
2016/07/26  13:13           230,334 main.cpp.obj
2016/07/26  13:13           240,154 menu.cpp.obj
2016/07/26  13:13           237,566 multilineentry.cpp.obj
2016/07/26  13:13           231,124 parent.cpp.obj
2016/07/26  13:13           234,452 progressbar.cpp.obj
2016/07/26  13:13           333,190 radiobuttons.cpp.obj
2016/07/26  13:13             1,952 resources.rc.obj
2016/07/26  13:13           233,027 separator.cpp.obj
2016/07/26  13:13           228,376 sizing.cpp.obj
2016/07/26  13:13           234,613 slider.cpp.obj
2016/07/26  13:13           238,362 spinbox.cpp.obj
2016/07/26  13:13           230,823 stddialogs.cpp.obj
2016/07/26  13:13           384,441 tab.cpp.obj
2016/07/26  13:13           230,025 tabpage.cpp.obj
2016/07/26  13:13           229,062 text.cpp.obj
2016/07/26  13:13           261,002 utf16.cpp.obj
2016/07/26  13:13           227,472 utilwin.cpp.obj
2016/07/26  13:13           478,741 window.cpp.obj
2016/07/26  13:13           227,880 winpublic.cpp.obj
2016/07/26  13:13           231,878 winutil.cpp.obj
```

I run the cmake commond with --trace, it shows:

```
E:\Workspace\libui\libui-build>e:\Tools\cmake\bin\cmake.exe --trace -E copy E:\W
orkspace\libui\libui-build\CMakeFiles\libui.dir\windows\resources.* E:\Workspace
\libui\libui-build\out\libui.res
Running with trace output on.
CMake Error: The source directory "E:/Workspace/libui/libui-build/out/libui.res"
 does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

It considers libui.res as directory.

I change libui.dir\build.make, replacing resources.rc.* back to resources.rc.obj, and it works well.

Is it cmake's problem?

**Comment by andlabs** [comment]
I don't know. The resource file stuff is a mess :S

**Comment by ptriller** [comment]
Its Windows problem. the "CMD" shell does no wildcard expansion, so it only works when you run it from a mingw bash with the "*"

**Pull request merged**
