### PR TITLE
Fix void* warning

### PR DESCRIPTION
**Pull request by kainjow**
"Format specifies type 'void *' but the argument has type 'uiWindow *' (aka 'struct uiWindow *')"

### CODE REVIEW

**Comment by andlabs** [comment]
There are more such warnings elsewhere; I'm not even sure why it happens o_O

**Comment by HalosGhost** [comment]
Because ``printf()``'s ``%p`` specifier expects a ``void *``:

From ``printf(3)``:

>        p      The void * pointer argument is printed in hexadecimal (as if by %#x or %#lx).

This is probably mostly harmless, but doing the explicit casts to avoid the warning output should cause no issues; so if the goal is a completely clean build, this should be replicated anywhere that does something similar.

**Comment by kainjow** [comment]
I only fixed the warnings I saw, which was from clang on OS X, so I'm sure there are other similar issues on the other platform code.

**Comment by andlabs** [comment]
Right, I mean why other pointer types aren't treated as `void *` like they would in any other context in C. I can fix this, but I'd like to know why this is a problem in the first place...

**Comment by andlabs** [comment]
Why kill the branch? I was going to apply it

**Comment by kainjow** [comment]
Hmm, I thought GitHub would retain it for the pull request. Are you not able to merge anymore?

**Comment by andlabs** [comment]
@kainjow no, github disables reopening the PR if the branch is deleted.

----

@HalosGhost and I think this might be strict format argument checking at play. I'll ask the compiler guys...

**Comment by kainjow** [comment]
Interesting discussion about it here:

https://www.quora.com/Is-it-undefined-behavior-if-I-dont-use-void*-when-I-use-p-format-specifier-in-C#!n=12

**Comment by andlabs** [comment]
Yep, that explains it; thanks!

**Pull request merged**
