### PR TITLE
Crash on pressing enter or escape

### PR DESCRIPTION
**Pull request by Vishal1707**

### CODE REVIEW

**Comment by andlabs** [comment]
Submitting someone else's pull request as your own isn't going to make me more inclined to take it, especially since it also includes extra work that I don't know anything about.

**Comment by Vishal1707** [comment]
Apologies @andlabs n @lxn, it was not intentional.

**Comment by andlabs** [comment]
It's fine; just note that you should see if someone has already made an open PR for a fix before making one yourself, and watch out for any extra commits that leak in.

**Comment by andlabs** [comment]
The main fix is already in master.

The other commit this includes now has separate discussion in https://github.com/Araq/libui/commit/0cc893df6f67d6c2f9e2ce3e6c24b66a1efaaf2a, since it's incorrect anyway.

Sorry again for yelling.

**Pull request closed without merging**
