### PR TITLE
Remove GTK timer source ID from main context on uninit

### PR DESCRIPTION
**Pull request by gdiv**
Restarting the main loop without removing the timer source results in
null-pointer dereference error in GTK.

https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#mainloop-memory-management

### CODE REVIEW

**Comment by ak-coram** [comment]
> What are you trying to do here? uiUninit() isn't supposed to be followed by anything else...

What's the purpose of `uiUninit()`then?

**Comment by cody271** [comment]
This looks correct to me FWIW. I thought `uiUninit()` should consistently clean up all global state..

**Comment by gdiv** [comment]
> What are you trying to do here? `uiUninit()` isn't supposed to be followed by anything else...

Two things.

1. proper cleanup (that's consistent with GTK documentation)
2. being able to start the whole UI again without killing the process which is helpful in dynamic languages like Python during dev time

**Comment by cody271** [comment]
> being able to start the whole UI again without killing the process which is helpful in dynamic languages like Python during dev time

Very useful for implementing hot reload in language bindings! :+1:

**Comment by andlabs** [comment]
Okay, hot-reloading would require a bit more work than just this, but this PR would be a start to that. I'm leaning toward letting this idea wait until after I do the Alpha 5 cleanups, but eh.

**Pull request closed without merging**
