### PR TITLE
unix: fixes segfaults in window.c

### LINKED ISSUE #165: unix: segmentation fault
```
Thread 1 "main" received signal SIGSEGV, Segmentation fault.
0x00000000010f40d0 in ?? ()
(gdb) bt
#0  0x00000000010f40d0 in ?? ()
#1  0x00000000007aacae in onConfigure (win=0x1020df0, e=0x10f0ee0, data=0x105b020) at /home/simon/projects/libui/unix/window.c:53
#2  0x00007ffff721372c in ?? () from /usr/lib/libgtk-3.so.0
#3  0x00007ffff5973fa5 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#4  0x00007ffff5985fb2 in ?? () from /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff598e6bf in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff598efff in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff73557bc in ?? () from /usr/lib/libgtk-3.so.0
#8  0x00007ffff7212784 in gtk_main_do_event () from /usr/lib/libgtk-3.so.0
#9  0x00007ffff6d49735 in ?? () from /usr/lib/libgdk-3.so.0
#10 0x00007ffff6d766a2 in ?? () from /usr/lib/libgdk-3.so.0
#11 0x00007ffff569edd7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#12 0x00007ffff569f040 in ?? () from /usr/lib/libglib-2.0.so.0
#13 0x00007ffff569f362 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#14 0x00007ffff7211a55 in gtk_main () from /usr/lib/libgtk-3.so.0
#15 0x00000000007a757d in uiMain () at /home/simon/projects/libui/unix/main.c:37
#16 0x0000000000469630 in runtime.asmcgocall () at /usr/lib/go/src/runtime/asm_amd64.s:582
#17 0x000000c8200216d8 in ?? ()
#18 0x000000000041017a in runtime.cgocall (fn=0xdbd100 <runtime.work+192>, arg=0x7fffffffe790, ~r2=14406048) at /usr/lib/go/src/runtime/cgocall.go:110
#19 0x000000000043df60 in runtime.startTheWorldWithSema () at /usr/lib/go/src/runtime/proc.go:986
#20 0x0000000000dbd100 in runtime.work ()
#21 0x00007fffffffe790 in ?? ()
#22 0x0000000000dbd1a0 in runtime.work ()
#23 0x000000000043dfd2 in runtime.mstart () at /usr/lib/go/src/runtime/proc.go:1068
#24 0x0000000000467a68 in runtime.rt0_go () at /usr/lib/go/src/runtime/asm_amd64.s:149
#25 0x0000000000000001 in ?? ()
#26 0x00007fffffffe8a8 in ?? ()
#27 0x0000000000000001 in ?? ()
#28 0x00007fffffffe8a8 in ?? ()
#29 0x0000000000000000 in ?? ()
```

### PR DESCRIPTION
**Pull request by emersion**
Fixes #165

### CODE REVIEW

**Comment by andlabs** [comment]
Are you sure this fixes segfaults after a clean build?

**Comment by emersion** [comment]
Just re-done the whole process, and segfaults are still here...

**Comment by andlabs** [comment]
That's definitely worth investigating then. I'm somehow getting a configure-event between connecting the configure signal and setting the default handler. That shouldn't happen; the main loop isn't running...

**Comment by andlabs** [comment]
Notes: turns out the issue was something else.

**Pull request closed without merging**
