### PR TITLE
fix static build on OpenBSD

### PR DESCRIPTION
**Pull request by jkusniar**
I'm not a CMake guru, but this did the trick.

### CODE REVIEW

**Comment by jkusniar** [comment]
--localize-hidden not supported by openbsd

**Comment by andlabs** [comment]
Then this is still an open issue.

**Comment by andlabs** [comment]
#308 will remove the need for this as the code this affects will no longer be necessary.

**Comment by andlabs** [comment]
Does the latest version of libui fail to build on OpenBSD?

**Comment by andlabs** [comment]
Friendly poke

**Comment by jkusniar** [comment]
Hi Pietro,

sadly, I have abandoned my Golang + OpenBSD activities and don’t have access to BSD machine anymore.

Regards
Jan Kusniar

**Comment by andlabs** [comment]
All right, thanks.

**Pull request closed without merging**
