### PR TITLE
Correct readme travis badge

### PR DESCRIPTION
**Pull request by ForsakenHarmony**

### CODE REVIEW

**Comment by andlabs** [comment]
Interesting. What branch was it using before? The one with the most recent commit?

**Comment by ForsakenHarmony** [comment]
I think it's just the latest build

**Comment by caspervonb** [comment]
> On the pages on Travis CI, we show the result of the most recent build on its default branch. For example, for docs-travis-ci-com, this is the master branch.

In other words, the master branch.

**Comment by tobbez** [comment]
Note the qualification in that statement: *On the pages on Travis CI*. That means it only applies to pages on the Travis CI site.

This is evident right now:

* The badge in the README (URL: https://travis-ci.org/andlabs/libui.svg) shows as failing
* The badge on the Travis CI site (URL: https://travis-ci.org/andlabs/libui.svg?branch=master) shows as passing.

Quite a few people likely takes the build appearing to fail as another sign that the project is dead (despite the project description), so it would probably be a good idea to merge this pull request.

**Comment by andlabs** [comment]
Ah, I'm seeing the badge discrepancy now. Fixing.

**Pull request merged**
