### PR TITLE
Cmake improvements

### PR DESCRIPTION
**Pull request by billyquith**
Naming. Logic.

### CODE REVIEW

**Comment by andlabs** [comment]
Declaring `project()` at the top is wrong, as there are several  properties there that must be set before `project()`. Note the comments.

**Comment by andlabs** [comment]
As for the shared library stuff, @kainjow was talking about something built into cmake that's a much better way to handle that than what I am doing now...

**Comment by billyquith** [comment]
> Declaring project() at the top is wrong, as there are several properties there that must be set before project(). 

Where did you read this?

**Comment by billyquith** [comment]
Travis install failed for this, not the changes.

```
W: There is no public key available for the following key IDs:
1397BC53640DB551
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I haven't seen any CMake projects where the main project isn't declared first. The project, according to their docs, just sets a name. It is the scoping that is important, not the order. Whatever exists in the scope at the end of the file is baked into the targets AFAIK.

**Comment by andlabs** [comment]
This PR is no longer relevant due to the CMake files having been rewritten since it was first proposed. Thanks though!

**Pull request closed without merging**
