### PR TITLE
chore(readme): add the link to arch linux aur

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by andlabs** [comment]
I will consider merging this once the library gets more stable and gets actual documentation. It now has install rules, so it should be safe to use now, but eh.

**Comment by actionless** [comment]
now?

**Comment by andlabs** [comment]
On the next packaged release, so I can consider the library stable to use (and hopefully other distributions will follow).

**Comment by actionless** [comment]
i was asking because i found few mentions of your lib in few different internet media almost at the same time (about few weeks ago) so i thought it was a movement from your side to announce it

**Comment by andlabs** [comment]
Merging now. How will the AUR choose between stable and unstable releases?

**Comment by actionless** [comment]
usually it's naming convention for AUR package, ie `libui` for stable, `libui-git` for latest git version

**Comment by andlabs** [comment]
All right, thanks! Enjoy using the AUR package.

**Pull request merged**
